version: '3.8'

services:
  mongo:
    image: mongo:latest
    command: >
      bash -c "
      if [ ! -f /etc/secrets/mongo-keyfile ]; then
        mkdir -p /etc/secrets &&
        openssl rand -base64 756 > /etc/secrets/mongo-keyfile &&
        chmod 400 /etc/secrets/mongo-keyfile
      fi &&
      mongod --replSet rs0 --bind_ip_all --keyFile /etc/secrets/mongo-keyfile
      "
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "mongo_data:/data/db"
    healthcheck:
      test: ["CMD-SHELL", "echo 'rs.status()' | mongosh --username root --password example --quiet || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:

